language: go

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"
  - "master"

notifications:
  email:
    on_success: never
    on_failure: always
