version: "2.0"

services:
  active_service:
    image: alpine
    entrypoint: /bin/sh
    command: ["-c", "while true; do echo 'active_service running'; sleep 1; done"]
    depends_on:
      - move_data_to_active_service

  new_service:
    image: alpine
    entrypoint: /bin/sh
    command: ["-c", "while true; do echo 'new_service running'; sleep 1; done"]
    depends_on:
      - prepare_new_service_version

steps:
  pre_prepare_0:
    image: alpine
    command: "echo \"Step pre_prepare_0\""

  pre_prepare_1:
    image: alpine
    command: "echo \"Step pre_prepare_1\""

  prepare_new_service_version:
    image: alpine
    command: "echo \"Step prepare_new_service_version\""
    after:
      - pre_prepare_0
      - pre_prepare_1

  wait_for_new_service:
    image: alpine
    command: "echo \"Step wait_for_new_service\""
    after:
      - new_service

  test_new_service:
    image: alpine
    command: "echo \"Step test_new_service\""
    after:
      - wait_for_new_service

  move_data_to_active_service:
    image: alpine
    command: "echo \"Step move_data_to_active_service\""
    after:
      - test_new_service
